# Build script
init:
  - git config --global core.autocrlf true
  
branches:
  only:
    - development
    - master

before_build:
  - dotnet restore src\

build_script:
  - dotnet build src\SharpNL.sln