# Build script
image: Visual Studio 2017

# Ignore shenanigans
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

cache:
  - '%LOCALAPPDATA%\Microsoft\dotnet -> appveyor.yml'
  - '%USERPROFILE%\.nuget\packages -> appveyor.yml, **\*.csproj, Nuget.Config'

init:
  - git config --global core.autocrlf true
  
branches:
  only:
    - development
    - master

before_build:
  - dotnet --version
  - appveyor-retry dotnet restore .\src\SharpNL
  - appveyor-retry dotnet restore .\src\SharpNL.Tests
  - appveyor-retry nuget restore .\src\

build_script:
  - dotnet build .\src\SharpNL\SharpNL.csproj
  - dotnet build .\src\SharpNL.Tests\SharpNL.Tests.csproj

test_script:
#  - dotnet test .\src\SharpNL.Tests\SharpNL.Tests.csproj
  - nunit3-console .\src\SharpNL.Tests\bin\Debug\SharpNL.Tests.exe --result=myresults.xml;format=AppVeyor

after_test:
  - dotnet build .\src\SharpNL\SharpNL.csproj --configuration=Release
  - dotnet pack .\src\SharpNL --configuration=Release --output=".\nuget"

artifacts:
- path: .\src\SharpNL\nuget\*.nupkg

deploy:
  - provider: NuGet
    api_key:
      secure: adAqjcxtMrAXUvmDp9Yz7tGGH4ja1jw6hRqKQy1axwk4OJ54rSPMavZceogalq5C
    skip_symbols: true
    on:
      branch: master