# Build script
image: Visual Studio 2017

# Ignore shenanigans
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

init:
  - git config --global core.autocrlf true
  
branches:
  only:
    - development
    - master

build_script:
  - dotnet restore src\
  - dotnet build src\SharpNL.sln

test_script:
  - dotnet restore src\SharpNL.Tests\
  - dotnet test src\SharpNL.Tests\SharpNL.Tests.csproj